---
- name: Ensure Docker Python library is installed
  pip:
    name: docker-py

- name: Populate Service facts
  service_facts:

- name: Show service facts
  debug:
    msg: "{{ ansible_facts.services }}"

- include_tasks: grafana.yml
- include_tasks: node-exporter.yml

