---
- name: Ensure docker python library is installed
  pip:
    name: docker-py

- name: Create Grafana docker container
  docker_container:
    name: "{{ metrics_grafana_container_name }}"
    image: "{{ metrics_grafana_container_image }}"
    state: present
    ports:
      - "80:3000"
    env:
      GF_DEFAULT_INSTANCE_NAME: "{{ metrics_grafana_instance_name }}"
      GF_SECURITY_ADMIN_USER: "{{ metrics_grafana_admin_username }}"
      GF_SECURITY_ADMIN_PASSWORD: "{{ metrics_grafana_admin_password }}"
      GF_AUTH_ANONYMOUS_ENABLED: "{{ metrics_grafana_anonymous_auth_enabled }}"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "{{ metrics_grafana_anonymous_auth_org_role }}"
      GF_INSTALL_PLUGINS: "{{ metrics_grafana_plugins }}"
      GF_SERVER_DOMAIN: "{{ metrics_grafana_domain }}"
      GF_SERVER_ROOT_URL: "http://{{ metrics_grafana_domain }}:80"

- name: Copy Grafana Systemd unit file
  template:
    src: "templates/grafana.service.j2"
    dest: "/lib/systemd/system/grafana.service"

- name: Enable and start Grafana service
  systemd:
    name: grafana
    state: started
    enabled: true

