---
- name: Create Prometheus group
  group:
    name: prometheus
    state: present

- name: Create Prometheus user
  user:
    name: prometheus
    group: prometheus

- name: Create directories for Prometheus
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: prometheus
  with_items:
    - "{{ metrics_prometheus_data_directory_host }}"
    - "{{ metrics_prometheus_config_directory_host }}"

- name: Copy Prometheus configuration file
  template:
    src: "templates/prometheus.yml.j2"
    dest: "{{ metrics_prometheus_config_host }}"
 
- name: Create Prometheus docker container
  docker_container:
    name: "{{ metrics_prometheus_container_name }}"
    image: "{{ metrics_prometheus_container_image }}"
    state: present
    ports:
      - "9090:9090"
    volumes:
      - "{{ metrics_prometheus_config_host }}:/etc/prometheus/prometheus.yml:ro"
      - "{{ metrics_prometheus_data_directory_host }}:/prometheus"

- name: Copy Prometheus Systemd unit file
  template:
    src: "templates/prometheus.service.j2"
    dest: "/lib/systemd/system/prometheus.service"

- name: Enable Prometheus service
  systemd:
    name: prometheus
    enabled: true
  when: ansible_facts.services['prometheus.service'] is defined and ansible_facts.services['prometheus.service']['status'] == "disabled"

- name: Start Prometheus service
  systemd:
    name: prometheus
    state: started
    daemon_reload: true

